
// Build.gradle generated for instrumentation module opensearch-java-client

apply plugin: 'java'

targetCompatibility=JavaVersion.VERSION_11

dependencies {
   implementation 'org.opensearch.client:opensearch-java:2.2.0'
   implementation 'org.opensearch.client:opensearch-rest-client:2.4.1'
   implementation 'org.apache.httpcomponents.client5:httpclient5:5.1.4'

   // New Relic Java Agent dependencies
   implementation 'com.newrelic.agent.java:newrelic-agent:8.4.0'
   implementation 'com.newrelic.agent.java:newrelic-api:8.4.0'
   implementation fileTree(include: ['*.jar'], dir: '../libs')
   implementation fileTree(include: ['*.jar'], dir: '../test-lib')
}

jar {
  manifest {
    attributes 'Implementation-Title': 'com.newrelic.instrumentation.labs.opensearch-java-client'
    attributes 'Implementation-Vendor': 'New Relic Labs'
    attributes 'Implementation-Vendor-Id': 'com.newrelic.labs'
    attributes 'Implementation-Version': 1.0
  }
}

verifyInstrumentation {
   passesOnly 'org.opensearch.client:opensearch-java:[2.2.0,2.25.0)'
}